version: '3.8'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: beribo
      POSTGRES_USER: postgres
      POSTGRES_DB: delivery
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
  serv:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    depends_on:
      - db
    ports:
      - '2503:2503'
    environment:
      POSTGRES_HOST: db
      NODE_ENV: production
      POSTGRES_PASSWORD: beribo
      POSTGRES_USER: postgres
      POSTGRES_DB: delivery
      PORT: 2503
      HOST: 0.0.0.0
